name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install PHP dependencies
        run: composer install

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate site with Sculpin
        run: vendor/bin/sculpin generate --env=prod

      - name: Push build to gh-pages branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output_prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          MESSAGE: "Build of {long-sha} ({msg})"
